from pathlib import Path

from setuptools import find_packages, setup

# Read the contents of README file
source_root = Path(".")
with (source_root / "README.md").open(encoding="utf-8") as f:
    long_description = f.read()

# Read the requirements
with (source_root / "requirements.txt").open(encoding="utf8") as f:
    requirements = f.readlines()

version = "0.0.3"

with (source_root / "src" / "pandas_time_profiling" / "version.py").open(
    "w", encoding="utf-8"
) as f:
    f.writelines(
        [
            '"""This file is auto-generated by setup.py, please do not alter."""\n',
            f'__version__ = "{version}"\n',
            "",
        ]
    )

setup(
    name="pandas-time-profiling",
    version=version,
    author="Daniel Wlazlo",
    author_email="daniel.wlazlo.external@axa.com",
    packages=find_packages("src"),
    package_dir={"": "src"},
    url="https://github.axa.com/daniel-wlazlo-external/pandas-time-profiling",
    license="MIT",
    description="Generate profile report for pandas DataFrame regarding time variable",
    python_requires=">=3.6",
    install_requires=requirements,
    extras_require={
        "notebook": [
            "jupyter-client>=6.0.0",
            "jupyter-core>=4.6.3",
            "ipywidgets>=7.5.1",
        ],
    },
    package_data={
        "pandas_time_profiling": ["py.typed"],
    },
    include_package_data=True,
    classifiers=[
        "Development Status :: 1 - Planning Copy",
        "Topic :: Software Development :: Build Tools",
        "License :: OSI Approved :: MIT License",
        "Environment :: Console",
        "Operating System :: OS Independent",
        "Intended Audience :: Science/Research",
        "Intended Audience :: Developers",
        "Intended Audience :: Financial and Insurance Industry",
        "Intended Audience :: Healthcare Industry",
        "Topic :: Scientific/Engineering",
        "Framework :: IPython",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
    ],
    keywords="pandas data-science data-analysis python jupyter ipython pandas-profiling",
    long_description=long_description,
    long_description_content_type="text/markdown",
    options={"bdist_wheel": {"universal": True}},
)